# Generated by Django 3.2.3 on 2021-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(max_length=10)),
                ('ename', models.CharField(max_length=40)),
                ('eemail', models.CharField(max_length=30)),
                ('econtact', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
